global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airphynet-inference'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'airphynet-ingestor'
    metrics_path: '/'
    static_configs:
      - targets: ['host.docker.internal:8001']

  - job_name: 'mongodb'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
